Develop
Nikolas7zip/java-explore-with-me pull request #2
Opened 2023-01-08 11:46 UTC by Nikolas7zip

Make ewm main and stats services

2023-01-08 18:24 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        if (event.getState() != EventState.PENDING) {
Почему бы не заимпортить статики?

`if (event.getState() != PENDING) {`

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/ewm/event/dto/GetEventsAdminRequest.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Сколько раз объявляешь одно и тоже?

`.ofPattern("yyyy-MM-dd HH:mm:ss")`

ну не так и много, на самом деле! )))

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/ewm/pagination/EntityPagination.java
> +    private int from;
Все поля могут быть `final`...

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/ewm/user/UserServiceImpl.java
> +        if (!userRepository.existsById(id)) {
Инвертируй метод и использую в условиях без отрицания `!`

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-stats/src/main/java/ru/practicum/ewm/StatsController.java
> +    @GetMapping("/stats")
А этот эндпоинт из того сервиса, кажется, не вызывается и не используется... как так получается?

2023-01-08 18:24 UTC, FanaticFiz commented on ewm-stats/src/main/resources/schema.sql
> +    uri             VARCHAR(255)    NOT NULL
Как для uri то очень мало выделено, тебе не кажется?

2023-01-08 18:24 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1</version>
Вопрос на засыпку, а зачем вообще приписывают `SNAPSHOT` и влияет ли это на что либо?

2023-01-09 15:22 UTC, Nikolas7zip commented on ewm-service/src/main/java/ru/practicum/ewm/pagination/EntityPagination.java
> +    private int from;
Так и сделаем)

2023-01-09 15:24 UTC, Nikolas7zip commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +import ru.practicum.ewm.event.QEvent;
Данный класс генерируется библиотекой querydsl, он потом попадает в target/generated-sources. Дополнительно в Intellij IDEA эта папка помечается как Generated Sources Root.

2023-01-09 15:27 UTC, Nikolas7zip commented on pom.xml
> +	<version>0.0.1</version>
Изучил вопрос, теперь знаю чуть больше) Спасибо!

2023-01-09 15:29 UTC, Nikolas7zip commented on ewm-stats/src/main/java/ru/practicum/ewm/StatsController.java
> +    @GetMapping("/stats")
Получается данный эндпоинт у меня используется при проверке, что в сервис статистики действительно сохранились данные по запросу. А количество просмотров у меня хранится в базе основного сервиса, чтобы не делать доп запросы на количество просмотров для группы мероприятий.

2023-01-09 15:44 UTC, Nikolas7zip commented on ewm-service/src/main/java/ru/practicum/ewm/category/Category.java
> +    @Column(name = "name", nullable = false)
Добавил!

2023-01-09 15:45 UTC, Nikolas7zip commented on ewm-stats/src/main/resources/schema.sql
> +    uri             VARCHAR(255)    NOT NULL
дело в том, что тут такие цели пока для статистики, что и этого много)

2023-01-09 16:55 UTC, Nikolas7zip commented on ewm-service/src/main/java/ru/practicum/ewm/event/dto/GetEventsAdminRequest.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Оставил по одному форматтеру на сервис)

2023-01-09 19:52 UTC, FanaticFiz approved these changes

2023-01-18 18:14 UTC, merged